# -*- coding: utf-8 -*-
"""Data Types and Variables

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBQATWWF0MhrtIV-x9P8_fOFD7YhCgjb
"""

Person_Name = 'James'
Person_Age = '70'
#Variables named according to name and age for program story


print("There once was a man named " + Person_Name + ",")
print("He was " + Person_Age + " years old.")
print("He really liked the name " + Person_Name + "","")
print("but he did not like being " + Person_Age + ".")