# -*- coding: utf-8 -*-
"""Triangle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBQATWWF0MhrtIV-x9P8_fOFD7YhCgjb
"""

print('   /|')
print('  / |')
print(' /  |')
print('/___|')